name: Release Builder

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Target Branch"
        required: true
        default: "master"
      tag:
        description: "Release Tag (格式: vX.Y.Z)"
        required: true
        default: "v1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
      
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Fix POM files
      run: |
        # 提取纯净版本号（去掉v前缀）
        VERSION=$(echo ${{ github.event.inputs.tag }} | sed 's/^v//')
        
        # 修复所有POM文件中的版本变量
        find . -name pom.xml -exec sed -i "s/\${dataease.version}/$VERSION/g" {} \;
        
        # 修复core模块的子模块引用（如果core-backend不存在）
        if [ ! -d "core/core-backend" ]; then
          sed -i '/<module>core-backend<\/module>/d' core/pom.xml
        fi
        
        # 打印修改后的POM文件用于调试
        echo "Modified POM files:"
        find . -name pom.xml -exec grep -l "<version>$VERSION</version>" {} \;
        
    - name: Build with Maven
      run: |
        # 先安装父POM
        mvn clean install -N -Dmaven.test.skip=true
        
        # 构建core模块及其子模块（排除不存在的模块）
        cd core
        mvn clean package -Pdesktop -U -Dmaven.test.skip=true
        
        # 查找生成的JAR文件
        JAR_PATH=$(find . -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" | head -n 1)
        if [ -z "$JAR_PATH" ]; then
          echo "::error::No JAR file found after build"
          exit 1
        fi
        echo "JAR_PATH=core/$JAR_PATH" >> $GITHUB_ENV
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag }}
        release_name: Release ${{ github.event.inputs.tag }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.JAR_PATH }}
        asset_name: CoreApplication-${{ github.event.inputs.tag }}.jar
        asset_content_type: application/java-archive